### PR TITLE
Move ENS checks to utils

### PR DESCRIPTION
**Pull request by dsimog01**
ENS names validation moved to utils and tests added:

The previous functions were marking strings like `example*.dappnode.eth`

### CODE REVIEW

**Review by pablomendezroyo — APPROVED** [review]

**Review by pablomendezroyo — CHANGES_REQUESTED** [review]
What is the rationale for this? looks like these functions are only used within those classes

**Review by pablomendezroyo — CHANGES_REQUESTED** [review]
@dsimog01 please don't forget this PR, I think it's a great improvement.

For me is just an organizational issue, these functions are only used within its classes so I would keep them inside with your modifications.

In the existing testing, I already create instances for each class, so take advantage of that and call the class function you need and implement your testing for the utility functions.

**Comment by dsimog01** [comment]
@pablomendezroyo I think that it is good to have exported `isEnsDomain` function as it is used also in the dappmanager, and we could remove duplicate code from there and import it from the toolkit that is already a dependency for the dappmanager

**Comment by pablomendezroyo** [comment]
Then it should be moved to types dependency and then use it here and in the dappmanager @dsimog01

**Comment by dsimog01** [comment]
> You are implementing testing for a dependency. Move the tests to the types repo

Fixed @pablomendezroyo

**Review by pablomendezroyo — APPROVED** [review]

**Pull request merged**
